services:
  vllm:
    image: public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo:v0.19.1
    volumes:
      - /sys:/sys:ro

    environment:
      HF_TOKEN: ${HF_TOKEN}

      VLLM_CPU_KVCACHE_SPACE: "2"
      VLLM_CPU_OMP_THREADS_BIND: "1"

      # FIX NUMA CRASH
      VLLM_CPU_NUMA_POLICY: "disabled"
      VLLM_CPU_BIND_THREADS: "0"
      OMP_NUM_THREADS: "4"
      MKL_NUM_THREADS: "4"
      OPENBLAS_NUM_THREADS: "4"

    command: >
      vllm serve ${HF_MODEL_ID}
      --host 0.0.0.0
      --port 8000
      --dtype float16