"""initial tables

Revision ID: 754ca6684f14
Revises: 23bad07600c8
Create Date: 2026-02-25 10:04:04.466453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754ca6684f14'
down_revision: Union[str, None] = '23bad07600c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagrams', 'cache_hit')
    op.drop_column('solutions', 'cache_hit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('cache_hit', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('diagrams', sa.Column('cache_hit', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
