"""initial tables

Revision ID: 75ac6d7e33e6
Revises: 754ca6684f14
Create Date: 2026-02-25 10:29:10.362692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ac6d7e33e6'
down_revision: Union[str, None] = '754ca6684f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagrams', 'model_used')
    op.drop_column('solutions', 'model_used')
    op.drop_column('solutions', 'generation_time_ms')
    op.drop_column('solutions', 'token_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solutions', sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('solutions', sa.Column('generation_time_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('solutions', sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('diagrams', sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

