from .dsl import DSL_SPEC, DSL_INFERENCE_INSTRUCTION, DATASET_GENERATION_PROMPT
from .solver import SOLVER_SYSTEM_PROMPT

__all__ = [
    "DSL_SPEC",
    "DSL_INFERENCE_INSTRUCTION",
    "DATASET_GENERATION_PROMPT",
    "SOLVER_SYSTEM_PROMPT",
]

